Add option to sentAt field to be null
segmentio/analytics-java pull request #345
Opened 2022-04-29 04:22 UTC by edsonjab

Override method create on Batch class to lend to user define his own date on sentAt field or use a null value.

Issue #340

2022-05-02 18:56 UTC, pooyaj commented
@edsonjab please check out the comment on the issue: https://github.com/segmentio/analytics-java/issues/340

2022-05-05 17:10 UTC, wenxi-zeng requested changes
the changes does not address the issue, since `Batch.create()` is only used internally to create a batch. 

you'll need to do the following:
1. in `Message` add a new nullable field `sentAt`
2. in `MessageBuilder` add a new field `sentAt` and make changes accordingly. you can take `userId` as an example for what needs to be done
3. in `MessageBuilder.realBuild` add a new parameter `sentAt` and make changes accordingly. 
4. discard all your changes in `Batch`. in `create` method do the following
```java
if any message in batch has `sentAt` not null
    use that value to create batch
otherwise
    use `new Date()` to create batch
```

now the users can use `builder.sentAt()` to modify the value

2022-05-05 21:27 UTC, wenxi-zeng commented on analytics-core/.factorypath
> +<factorypath>
is this one accidentally checked in?

2022-05-05 21:27 UTC, wenxi-zeng commented on analytics-core/src/main/java/com/segment/analytics/messages/Batch.java
> +  @Nullable
no need to be nullable here

2022-05-05 21:27 UTC, wenxi-zeng commented on analytics-core/src/test/java/com/segment/analytics/messages/BatchTest.java
> +  public void createWithSentAt(TestUtils.MessageBuilderFactory factory) throws ParseException {
better to have another test with messages has `sentAt` as nulls, so we have both paths covered.

2022-05-05 21:35 UTC, wenxi-zeng approved these changes
rest LGTM

2022-05-05 22:12 UTC, pooyaj approved these changes

2022-05-05 22:12 UTC, merged